Include URL in case of HTTP error
Instead of:

    urllib.error.HTTPError: HTTP Error 404: Not Found

it will now show:

    RuntimeError: HTTP Error: 404 for URL: https://api.frankfurter.app/latest?base=USD&symbols=RUB